services:
  # 1. Python AI Service
  - type: web
    name: examseva-ai
    env: docker
    rootDirectory: python_ai
    # Build and start commands are defined in the Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        generateValue: true

  # 2. Node.js Backend Service
  - type: web
    name: examseva-backend
    env: node
    rootDirectory: backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://examseva:examseva@cluster0.s2jwqdu.mongodb.net/examsevaDB?appName=Cluster0
      - key: PYTHON_URL_BASE
        fromService:
          type: web
          name: examseva-ai
          envVar: RENDER_EXTERNAL_URL
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true

  # 3. React Frontend Static Site
  - type: static
    name: examseva-frontend
    buildCommand: "npm install && GENERATE_SOURCEMAP=false npm run build"
    publishPath: "./build"
    rootDirectory: frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: examseva-backend
          envVar: RENDER_EXTERNAL_URL
